### ISSUE TITLE
add 'choo' as an alternative bin command

### ISSUE THREAD

**Issue by Flet** [choojs/choo-scaffold#4]
Typing `choo-scaffold` is a lot for my poor fingers!

Adding `choo` under 'bin' in package.json would let us type this instead:
```bash
# Create a new store
$ choo store todos

# Create a new view
$ choo view 404
```

Ahhhh, much better!

**Comment by YerkoPalma** [comment]
This would conflict with [choo-cli](https://github.com/trainyard/choo-cli)

**Comment by Flet** [comment]
doh!

**Comment by yoshuawuyts** [comment]
I was thinking that by adding it to `create-choo-app`, the result would be:
```sh
# Create a new store
$ npm run create store todos

# Create a new view
$ npm run create view 404
```

In turn, if that's too much typing, you could alias `npm run` to `nr` or `npr`

```sh
# Create a new store
$ npr create store todos
$ npr create view 404
```

Requires a little tweakage, but might go a long way (:

**Comment by yoshuawuyts** [comment]
Think this has been resolved. Closing for now!
